package error

var errorMap = map[string]map[string]string{
	"en": {
		"invalid_request":     "Invalid request",
		"invalid_token":       "Invalid token",
		"invalid_credentials": "Invalid credentials",
		"invalid_user":        "Invalid user",
		"invalid_password":    "Invalid password",
		"invalid_email":       "Invalid email",
		"invalid_phone":       "Invalid phone",
		"invalid_name":        "Invalid name",
		"invalid_id":          "Invalid id",
		"invalid_code":        "Invalid code",
		"invalid_status":      "Invalid status",
		"invalid_type":        "Invalid type",
		"Otp_expired":         "Otp expired",
		"Otp_invalid":         "Otp invalid",
		"Otp_not_match":       "Otp not match",
		"Otp_not_send":        "Otp not send",
		"Otp_send_failed":     "Otp send failed",
		"Otp_send_success":    "Otp send success",
		"Email_exist":         "Email exist",
		"Username_exist":      "Username exist",
		"Phone_exist":         "Phone exist",
		"Permission_denied":   "Permission denied",
		"Record_not_found":    "Record not found",
	},
	"vi": {
		"invalid_request":     "Yêu cầu không hợp lệ",
		"invalid_token":       "Token không hợp lệ",
		"invalid_credentials": "Thông tin đăng nhập không hợp lệ",
		"invalid_user":        "Người dùng không hợp lệ",
		"invalid_password":    "Mật khẩu không hợp lệ",
		"invalid_email":       "Email không hợp lệ",
		"invalid_phone":       "Số điện thoại không hợp lệ",
		"invalid_name":        "Tên không hợp lệ",
		"invalid_id":          "Id không hợp lệ",
		"invalid_code":        "Mã không hợp lệ",
		"invalid_status":      "Trạng thái không hợp lệ",
		"invalid_type":        "Loại không hợp lệ",
		"Otp_expired":         "Otp hết hạn",
		"Otp_invalid":         "Otp không hợp lệ",
		"Otp_not_match":       "Otp không khớp",
		"Otp_not_send":        "Otp chưa được gửi",
		"Otp_send_failed":     "Gửi otp thất bại",
		"Otp_send_success":    "Otp gửi thành công",
		"Otp_send_limit":      "Otp send ",
		"Email_exist":         "Email đã tồn tại",
		"Username_exist":      "Username đã tồn tại",
		"Phone_exist":         "Số điện thoại đã tồn tại",
		"Permission_denied":   "Không có quyền truy cập",
		"Record_not_found":    "Không tìm thấy bản ghi",
	},
}
